### ISSUE TITLE
New Favourite Icon

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#18]
An icon is needed to to be decided upon for the top left hand side / little icon that is displayed when a tab for our app will be used. The goal is at the moment to not use the Concordia Schedule Builder's logo but instead find something that represents both concordia and SOEN students and something ppl will recognize. If nothing is available to find, one can be made

**Comment by juliabaz** [comment]
![img_9212](https://user-images.githubusercontent.com/46771672/52757548-09c4ad00-2fd3-11e9-905e-cdfeb23bfc69.PNG)
