### ISSUE TITLE
Fix Front End Warnings

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#25]
Resolve the following warning signs from running the front end:

![warnings](https://user-images.githubusercontent.com/36492119/52168331-cf1b6480-26f6-11e9-9bda-7d3f92287c0a.png)

**Comment by alimahram** [comment]
lets go

**Comment by Averynder** [comment]
Runs much smoother & compilation is faster. Good job!
![fixed_warnings](https://user-images.githubusercontent.com/36492119/52480824-c1dcfa80-2b7a-11e9-90c4-aa5047164bd4.png)
