### ISSUE TITLE
Scripts to Repeatedly Connect

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#26]
This issue will require the user to run the test code to connect to the site but program an OS specific script that can run in cmd / bash and repeatedly run itself / does the program numerous times

**Comment by andrelegault** [comment]
What should I make the script test for? From what I got there should be test code that'll be used to connect to the site but nothing further than that. I'll look into making a platform-agnostic script instead of making three separate scripts for each type of OS though.

**Comment by Averynder** [comment]
that sounds alright with me but first someone needs to code a program TO connect to the site first before you can make any scripts to repeatedly run it
