### ISSUE TITLE
Create Database from Relational Schematic

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#46]
This will require the developer to apply the changes from the relational schematic (proper) to the database so that for future reference, our database will be fully set and won't require additional changes without the need for them.

**Comment by vicmanea** [comment]
I can do it boss

**Comment by vicmanea** [comment]
[341 Relational Schemas for ER Diagram 2.0.pdf](https://github.com/Averynder/cssd/files/2895154/341.Relational.Schemas.for.ER.Diagram.2.0.pdf)

Updated the Relational schematic to be more consistent and concise.
