### ISSUE TITLE
Logical View Class Diagram

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#55]
This task is for section 3.1 of the new deliverable.
Examples can be found on the moodle page from:
Colbat pg.98
Raccoons ph.46

**Comment by Rubiat** [comment]
![logical view](https://user-images.githubusercontent.com/39073538/53535977-96429580-3ad2-11e9-8d1a-51fa897b78b2.png)

**Comment by Rubiat** [comment]
![logical view](https://user-images.githubusercontent.com/39073538/53603302-10c8ef00-3b7f-11e9-84f8-27361e0729f6.png)

**Comment by Rubiat** [comment]
https://www.lucidchart.com/invitations/accept/e20f4475-7729-41f6-8adf-deaf674ceb47

**Comment by Rubiat** [comment]
![logical view](https://user-images.githubusercontent.com/39073538/53675056-cf107500-3c60-11e9-8977-2b8f7a09562c.png)
