### ISSUE TITLE
Component Diagram

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#56]
This task will be for section 3.1 for the developmental view.
Examples can be found in the finished documents on moodle:
Colbat pg.101
Raccoons pg.47

**Comment by vicmanea** [comment]
![component diagram 341-2](https://user-images.githubusercontent.com/36647329/53377716-f6013b00-3930-11e9-81a7-28727253f0db.png)

What I have so far. Can be reworked if we need more depth.
