### ISSUE TITLE
Activity Diagrams

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#58]
This issue will be for the process view in section 3.1 and examples can be found at:
Colbat pg.106
Raccoons pg.48

**Comment by juliabaz** [comment]
(UC4) https://www.lucidchart.com/invitations/accept/a486e489-0103-4728-8190-32318d0850a2
(UC5) https://www.lucidchart.com/invitations/accept/d91c42e4-ef81-4117-9341-ce2aea9c9696
