### ISSUE TITLE
Subsystems UML Class Diagrams

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#60]
This will be for section 4.1 from the deliverable and will require the user to create a similar diagram to the examples can be found in the finished documents on moodle:
Colbat pg.118-122
Raccoons pg.55-58

**Comment by Rubiat** [comment]
![subsystem 1](https://user-images.githubusercontent.com/39073538/53535919-65faf700-3ad2-11e9-80f2-ccf9eb90d847.png)

![subsystem 2](https://user-images.githubusercontent.com/39073538/53535930-70b58c00-3ad2-11e9-95ce-95a5cc47a4b3.png)

2 subsystems for now

**Comment by Rubiat** [comment]
![subsystem 1](https://user-images.githubusercontent.com/39073538/53603277-fabb2e80-3b7e-11e9-9778-4bedbbd0c4f9.png)

**Comment by Rubiat** [comment]
![subsystem 2](https://user-images.githubusercontent.com/39073538/53603284-fe4eb580-3b7e-11e9-99ae-762df36562e3.png)

**Comment by Rubiat** [comment]
![subsystem 1](https://user-images.githubusercontent.com/39073538/53675114-5231cb00-3c61-11e9-918b-0c1a53bf4382.png)

https://www.lucidchart.com/invitations/accept/07262b1c-0ad8-40ca-9ebc-f2ab4dbb944a

**Comment by Rubiat** [comment]
![subsystem 2](https://user-images.githubusercontent.com/39073538/53675141-98872a00-3c61-11e9-8c8e-695169bfbe09.png)

https://www.lucidchart.com/invitations/accept/373256ff-634c-46d4-8a2b-5ec192254544
