### ISSUE TITLE
Unit Descriptions

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#61]
This will require the user to create tables for section 4.2 also needing the work from the subsystems UML class diagrams to be completed.
Examples can be found in the finished documents on moodle:
Colbat pg.123-130
Raccoons pg.59-61

**Comment by Rubiat** [comment]
[Unit Descriptions.pdf](https://github.com/Averynder/cssd/files/2921608/Unit.Descriptions.pdf)
