### ISSUE TITLE
Scenano Sequence Diagrams

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#62]
This will be for section 5 and will require at least 2 user cases each having 3+ system operations.
Examples can be found in the finished documents on moodle:
Colbat pg.140-143
Raccoons pg.62-73

**Comment by h-karim** [comment]
Automatic sequence generation (UC4) : https://www.lucidchart.com/invitations/accept/4764c33c-f071-4fb6-b397-c4851bb224d4

Manual sequence generation (UC5) : https://www.lucidchart.com/invitations/accept/2ae15985-51bc-404e-84e7-2d3f3bb3cd3a
![manual sequence user case](https://user-images.githubusercontent.com/46734059/53679350-96ee4e00-3cc3-11e9-8e16-c1e09c1e7d67.png)
![automatic sequence generation uc4](https://user-images.githubusercontent.com/46734059/53679353-9bb30200-3cc3-11e9-9e2a-4ba0eb5a7e7f.png)
