### ISSUE TITLE
Using cookies to save log in

### ISSUE THREAD

**Issue by Averynder** [Averynder/cssd#9]
This will require that once the user enters in their information, we can load it directly from their browser using cookies so they don't have to type it in every single time

**Comment by andrelegault** [comment]
I suggest we use http://www.passportjs.org/docs/username-password/ for user authentication. Any thoughts?

**Comment by vicmanea** [comment]
> I suggest we use http://www.passportjs.org/docs/username-password/ for user authentication. Any thoughts?

Straightforward enough, I love it

**Comment by Averynder** [comment]
This issue had 3 objectives, and was already previously split into 2 issues. Andre's cookies was really to display info from the cookie to front end, thus only the first part remains with no knowledge. Accomplish this and use code from what was previously established.
1) get user input for user and pass
2) store in cookie
3) display cookie
